Traceback (most recent call last):
  File "/home/sarvesh/PythonProject/pythonscript/traceback1.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
